[package]
name = "kube-mock"
version = "0.1.0"
edition = "2021"
description = "Mock Kubernetes server for testing"


[dependencies]
k8s-openapi = { version = "0.23", features = ["latest"] }
kube = { version = "0.95", features = [] }
tokio = { version = "1.40", features = ["full"] }
